# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'JewelCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JewelCase
  pod 'TMDB'
  pod 'URLImage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
end
